const { chromium }=require('playwright');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const results=[]; const check=(name,pass,detail='')=>results.push({name,pass,detail});
 page.on('dialog',d=>d.dismiss());
 await page.goto('http://127.0.0.1:3000'); await page.locator('.mcard').first().waitFor();
 check('10 home cards',await page.locator('.mcard').count()===10);
 check('30 home showtime labels',await page.locator('.mcard-showtime').count()===30);
 await page.screenshot({path:'/tmp/ces-home.png',fullPage:true});
 await page.locator('input').fill('uNe'); await page.waitForTimeout(350);
 check('partial case-insensitive search',await page.locator('.mcard').count()===1 && (await page.locator('.mcard-title').innerText())==='Dune: Part Two');
 await page.locator('select').first().selectOption('Action'); await page.waitForTimeout(350);
 check('combined no match message',await page.locator('.no-results').count()===1);
 await page.locator('input').fill('');await page.waitForTimeout(350);
 check('genre returns four action movies',await page.locator('.mcard').count()===4);
 await page.locator('select').first().selectOption('');await page.waitForTimeout(350);
 check('clear restores ten',await page.locator('.mcard').count()===10);
 check('date disabled',await page.locator('select').nth(1).isDisabled());
 await page.locator('.mcard').first().click();await page.locator('iframe').waitFor();
 check('details fields and showtimes',await page.locator('.st-btn').count()===3 && (await page.locator('.detail-desc').innerText()).length>0);
 await page.screenshot({path:'/tmp/ces-detail.png',fullPage:true});
 await page.locator('.st-btn').nth(1).click(); await page.locator('.seat').first().waitFor();
 check('booking movie/time',(await page.locator('.booking-hdr').innerText()).includes('5:00 PM'));
 check('70 seats',await page.locator('.seat').count()===70);
 await page.locator('.seat:not(:disabled)').first().click();
 check('seat select',await page.locator('.seat.sel').count()===1);
 check('checkout enabled with zero tickets',await page.locator('.ck-btn').isEnabled());
 await page.locator('.seat.sel').click();check('seat deselect',await page.locator('.seat.sel').count()===0);
 for (let i of [1,3,5]) await page.locator('.qbtn').nth(i).click();
 check('ticket total 31.97',(await page.locator('.ot-amt').innerText())==='$31.97');
 await page.screenshot({path:'/tmp/ces-booking.png',fullPage:true});
 await page.clock.install();await page.reload();await page.locator('.seat').first().waitFor();
 await page.locator('.seat:not(:disabled)').first().click();await page.clock.runFor(301000);
 check('timer clears seats',await page.locator('.seat.sel').count()===0);
 const t=await page.locator('.timer-chip').innerText();await page.clock.runFor(10000);
 check('timer frozen after expiry',(await page.locator('.timer-chip').innerText())===t,t);
 await page.goto('http://127.0.0.1:3000/booking/1/nonsense');await page.locator('.booking-meta').waitFor();
 check('invalid showtime accepted',(await page.locator('.booking-meta').innerText()).includes('nonsense'));
 await page.goto('http://127.0.0.1:3000/booking/1/%25');await page.waitForTimeout(500);
 check('percent showtime crashes content',await page.locator('.booking-page').count()===0);
 await page.unrouteAll();await page.route('**/api/movies',r=>r.fulfill({json:[]}));
 await page.goto('http://127.0.0.1:3000');await page.locator('.no-results').first().waitFor();
 check('empty DB messages',await page.locator('.no-results').count()===2);
 await page.unrouteAll();await page.route('**/api/movies',r=>r.fulfill({status:500,json:{error:'fail'}}));
 await page.reload();await page.locator('.no-results').first().waitFor();
 check('API failure incorrectly shown as empty catalogue',await page.locator('.no-results').count()===2);
 await page.unrouteAll();
 await page.setViewportSize({width:375,height:812});await page.goto('http://127.0.0.1:3000/booking/1/5%3A00%20PM');await page.locator('.seat').first().waitFor();
 await page.screenshot({path:'/tmp/ces-mobile.png',fullPage:true});
 check('mobile body overflow',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
 fs.writeFileSync('/tmp/ces-browser-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
